### ISSUE TITLE
Forge version seems to require Kotlin for Fabric?

### ISSUE THREAD

**Issue by Wolris** [SettingDust/HeraclesForVillagers#6]
Minecraft 1.20.1
Forge 47.2.21

Minecraft loaded with the error screen and said as much.  Here is an excerpt from the error log:

net.minecraftforge.fml.ModLoadingException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
   - Install �6fabric-language-kotlin�r, version 1.10 or later.
More details:
   - �Emod HeraclesForVillagers (heracles_for_villagers)�r 0.3.1+sha.401648a requires version 1.10 or later of �6fabric-language-kotlin�r, which is missing!
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.20.1-47.2.21.jar%231507!/:?]
	at ... (ETC)

I do have many other mods installed (Including Heracles).  Full log is attached.

[latest.log](https://github.com/SettingDust/HeraclesForVillagers/files/14783587/latest.log)

**Comment by Wolris** [comment]
Oh, and Kotlin for Forge IS installed at 4.10.0

**Comment by SettingDust** [comment]
You should use connector function to provide fabric Kotlin from Kotlin forge

EDIT: https://sinytra.org/docs/connector/configuration#global-mod-aliases and add fabric Kotlin ID to Kotlin forge

For reference: https://github.com/Sinytra/Connector/issues/399
