### ISSUE TITLE
How exactly do I get this to work?

### ISSUE THREAD

**Issue by alarmgoose** [SettingDust/HeraclesForVillagers#8]
I've linked it using UUID but when talking to the villager, nothing happens. Using this with the Sin Connector with forge.

**Comment by SettingDust** [comment]
Create a quest with a villager/entity interact task and add a dialogue as reward

**Comment by alarmgoose** [comment]
![image](https://github.com/user-attachments/assets/10baa2b8-ecc8-4305-89dc-2b2b03ec34c9)
I did this above. Then I tried the following but I'm not seeing the dialogue as a reward...?
![image](https://github.com/user-attachments/assets/8f87215c-2d80-4342-abb2-84ae3b739d5d)
Am I just daft?

**Comment by SettingDust** [comment]
wait. What's the "talking" in your post?

**Comment by SettingDust** [comment]
feel free to comment for reopen
