### ISSUE TITLE
Incompatibility with Bean's Backapacks mod

### ISSUE THREAD

**Issue by shvrma** [SettingDust/HeraclesForVillagers#9]
On Minecraft ver. 1.20.1 with Quilt loader ver. 0.26.3 Heracles For Villagers causes backpacks not to open while placed on the ground nor be taken. Idk whether this issue should be addressed here or to the Beans Backpack's mod.

**Comment by shvrma** [comment]
Beans Backpacks ver. 2.0.2; Heracles For Villagers - 0.4.1

**Comment by SettingDust** [comment]
~~Is there any log?~~

Reproduced

**Comment by SettingDust** [comment]
My fault on logic. 

Fixed in 4ff73d5f7f10312428d3087d79f886317eb59c54 0.4.2
